name: task 3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name:  Set java version
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: 
        ./mvnw clean package spring-boot:repackage

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/jwt-auth-service-1.0.0.jar
        
    - name: Download artifact
      uses: actions/download-artifact@v4        

    - name: Run artifact
      run: java -jar target/jwt-auth-service-1.0.0.jar
